### ISSUE TITLE
webpage integration

### ISSUE THREAD

**Issue by TobiBu** [rodluger/showyourwork#23]
Hi,
I suggest to integrate the option to additionally create a webpage (e.g. GitHub page) to explain/highlight the science to the broader public. E.g. as it is common practise in the field of machine learning.

here a little random [example](https://www.matthewtancik.com/nerf)

**Comment by rodluger** [comment]
@TobiBu This is a good idea, but it's beyond the scope of what I'm able to implement right now. I'm happy to consider PRs, though, or integrations with existing workflows for scientific webpage generation. Closing this for now, but feel free to re-open.
