### ISSUE TITLE
Errors on new M1 macs

### ISSUE THREAD

**Issue by rodluger** [rodluger/showyourwork#32]
Snakemake segfaults on the newer Mac machines. I believe we can circumvent this by installing `snakemake-minimal` instead of `snakemake`, although that might break DAG generation.

**Comment by rodluger** [comment]
Working on a patch in the `M1` branch: https://github.com/rodluger/showyourwork/blob/M1/Makefile#L39-L44

@dfm, can you confirm that the command

```bash
sysctl -n machdep.cpu.brand_string
```

outputs a string containing `M1` on your system?

**Comment by dfm** [comment]
Confirmed:

```
> sysctl -n machdep.cpu.brand_string
Apple M1
```

**Comment by rodluger** [comment]
Thanks!
