### ISSUE TITLE
Update to fontawesome5 LaTeX package?

### ISSUE THREAD

**Issue by TomWagg** [rodluger/showyourwork#39]
showyourwork seems to use `fontawesome` rather than `fontawesome5` for icons in LaTeX. This means I can't do `usepackage{fontawesome5}` in my files because it conflicts with `usepackage{fontawesome}` in the showyourwork files.

Would you mind updating to the new fontawesome5 package? They've got a bunch of new icons, for example [laptop-code](https://fontawesome.com/v5.15/icons/laptop-code?style=solid) and [file-code](https://fontawesome.com/v5.15/icons/file-code?style=solid), which would be great to have access to ☺️

**Comment by rodluger** [comment]
Good suggestion! This has been implemented in `v0.1.22`. You should be able to run
```
make update
```
locally to update to this version of showyourwork.
