### ISSUE TITLE
Latex figure path needs to be hardcoded in every \includefigure, cannot use \graphicspath to define one path globally

### ISSUE THREAD

**Issue by mathren** [rodluger/showyourwork#44]
I have encountered a behavior that is likely intended, though could cause some headaches to new users -- might be worth adding a note about this in the docs (unless it is easily fixable).

In my normal workflow, to avoid typing the path for every figure as in `\includegraphics{path/to/figure/figure.pdf}` I usually add to my latex documents the graphics path as `\graphicspath{{./path/to/figure/}}` once right after the `\begin{document}`, and afterwards I can then just specify the file name (without its path relative to the tex file) when calling `\includegrapihcs`.

So for my showyourwork project I had `\graphicspath{{./figures/}}` and then where I include the figure just `\includegraphics{fig.pdf}` -- latex prepends to the file name the graphicspath on its own, and locally I can compile. However, this seems to break the snakemake flow (with the `\graphicspath` latex command, snakemake does not successfully build the figures.

I the docs should emphasize that (i) you really do need the whole path to a figure in `\includegraphics` and (ii) you cannot specify it once for the entire document using `\graphicspaths`. Alternatively showyourwork should try to see if such latex command has been used and prepend its argument to all the figure paths.

Minimal example tex file to reproduce the error (and how to fix it -- see 
```
\documentclass[twocolumn]{aastex631}

% Filler text
\usepackage{blindtext}

% Begin!
\begin{document}

% ----------------------------------------------------
%% comment line below to make things work
\graphicspath{{./figures/}
% ----------------------------------------------------

\begin{figure}[ht!]
  \begin{centering}
   % ----------------------------------------------------
    %% comment line below and uncomment the following to make things work
    \includegraphics[width=0.75\linewidth]{fibonacci.pdf}
    % \includegraphics[width=0.75\linewidth{./figures/fibonacci.pdf}
    % ----------------------------------------------------
    \caption{caption}
    % This label tells showyourwork that the script `figures/fibonacci.py'
    % generates the PDF included above
    \label{fig:fibonacci}
  \end{centering}
\end{figure}

\end{document}
```

**Comment by rodluger** [comment]
Thanks for raising this issue. It should be possible to implement what you need -- I'll look into it tomorrow.

**Comment by rodluger** [comment]
@mathren This should be fixed as of `v0.1.28`. Please feel free to re-open if you're still running into issues.

**Comment by rodluger** [comment]
@mathren See here: https://showyourwork.readthedocs.io/en/stable/custom/#using-graphicspath

**Comment by mathren** [comment]
I just gave it a try, works! Thank you!
