### ISSUE TITLE
Extension to `\input`

### ISSUE THREAD

**Issue by arm61** [rodluger/showyourwork#48]
Sorry for another feature request pretending to be an issue. 

Sometimes, I have a small tex snippets written to file by my analysis scripts, which are then ingested by my LaTeX document. For example, the mean value of some distribution that has been plotted. This means I don't have to faff around with numbers and they are automatically in the paper. 

This is possible currently, however, if any of the tex snippets are missing (i.e. they haven't been generated by the plotting/analysis code which hasn't run), the tex generation seems to fail on the first pass (I think when it is doing the introspection for the figure labels) because I am using `\input` which kills the compilation. 

Any ideas on a workaround for this? Or interest in extending the framework to `\input` (I am aware this is a big ask 😅)

**Comment by rodluger** [comment]
No problem, these requests all help make the code better!

How about specifying the ``\input`` file as a dependency, such as 

```
dependencies:
    - src/ms.tex:
        - src/mean_value.tex
```

? This isn't currently implemented but should be quite easy to do in the next release.

**Comment by arm61** [comment]
I think that will work. If I change the script that produces `src/mean_value.tex` would that be updated automatically or would I also need to identify that as a dependency? (say if the produced script was **not** a figure script).

**Comment by rodluger** [comment]
As long as you specify a custom rule in your ``Snakefile`` to produce ``mean_value.tex`` with explicit inputs, e.g.,

```
rule mean_value:
    input:
        src/compute_mean_value.py
    output:
        src/mean_value.tex
    shell:
        python src/compute_mean_value.py
```

then changes to ``src/compute_mean_value.py`` should propagate through the graph and trigger a re-run of the PDF build (thanks to ``Snakemake``, not ``showyourwork``!)

**Comment by rodluger** [comment]
Great, I'll implement this in the next patch.

**Comment by rodluger** [comment]
This has been implemented in `v0.1.29`. Please see this example: https://showyourwork.readthedocs.io/en/v0.1.29/custom/#custom-manuscript-dependencies

and feel free to re-open if you find any issues!

**Comment by arm61** [comment]
Looks like this is working beautifully!

**Comment by arm61** [comment]
Linking in with #35 will the txt files be carried over the the ArXiv tarball?

**Comment by rodluger** [comment]
They should -- let me know if you find they don't.
