### ISSUE TITLE
custom margin links

### ISSUE THREAD

**Issue by rodluger** [rodluger/showyourwork#55]
Add a LaTeX command to make it easy for users to include custom margin links (for static figures, or for figures generated by custom Snakemake commands).

**Comment by rodluger** [comment]
This is now implemented via a new `\marginicon{}` command on the LaTeX side: https://github.com/rodluger/showyourwork-example-dev/blob/custom-figure-link-pdf/ms.pdf

![image](https://user-images.githubusercontent.com/9323819/144665994-f6842141-f441-4911-ba8a-7c2515cb1ccf.png)

@tomwagg @afeinstein20 You might find this useful. This is implemented on the `main` branch and will be released in `v0.2.0` soon.

**Comment by TomWagg** [comment]
Oh very nice @rodluger, I'll definitely be using this for Fig. 1 of the [LEGWORK paper](https://github.com/TeamLEGWORK/LEGWORK-paper)!
