### ISSUE TITLE
ArXiv submission compiles hidden file in tarball

### ISSUE THREAD

**Issue by mathren** [rodluger/showyourwork#78]
When submitting to arxiv  [this tarball](https://github.com/mathren/top_down_compact_obj_mass/blob/submitted-pdf/arxiv.tar.gz) the automatic processing also compiles the hidden file `.showyourwork-xml-ms.tex`.This results in a doubled pdf.

I cleaned it up by hand, but probably there is a better way. This is using showyourwork v0.1.28, so might be fixed already.

Thanks for this awesome tool!

**Comment by rodluger** [comment]
Hmm, that file is temporary, and shouldn't be committed to the repository by default (see [this line](https://github.com/rodluger/showyourwork-template/blob/29bbb2b9ff430b2855488743ed50f155296ee51d/src/.gitignore#L12) in the gitignore of the template repository). You must have accidentally committed it (perhaps via a force-push)?
