### ISSUE TITLE
Zenodo linking during prototype stage

### ISSUE THREAD

**Issue by grburgess** [rodluger/showyourwork#79]
If one is working on a paper and the dataset is not published yet, is there a way to use secrets to give access to an unpublished dataset on Zenodo?

**Comment by rodluger** [comment]
That's a great question! Not currently, but that's one of the features I'm working on for the next release (`0.3.0`). One option currently is to use Zenodo sandbox during development -- just make a new version every time your dataset changes. On sandbox the deposits aren't associated with a real DOI, so there's no harm to making lots of revisions. But this would still make the dataset visible to the world during development. Are you worried about confidentiality or the fact that your dataset is not yet final?

**Comment by grburgess** [comment]
Confidentiality is low priority. More about building the article in stages, but with the ability to change the data around as things progress. I would just upload the data into the repo... but this data set is ~ 0.5GB

**Comment by grburgess** [comment]
So I have tried the sandbox option with a custom rule to download the data with curl.  But for some reason, the file rarely wants to download completely:


```
  rule jcg_db:
1412
      output: src/data/jcg_db.h5
1413
      jobid: 23
1414
      reason: Missing output files: src/data/jcg_db.h5
1415
      resources: tmpdir=/tmp
1416
  
1417
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
1418
                                   Dload  Upload   Total   Spent    Left  Speed
1419
  
1420
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
1421
  100  3002  100  3002    0     0   3738      0 --:--:-- --:--:-- --:--:--  3733
1422
  100  3002  100  3002    0     0   3738      0 --:--:-- --:--:-- --:--:--  3733
1423
  total 4.0K
1424
  -rw-r--r-- 1 runner docker 3.0K Feb  2 14:54 jcg_db.h5
1425
  [Wed Feb  2 14:54:06 2022]
1426
  Finished job 23.
1427
  16 of 19 steps (84%) done

```

The file is ~700 Mb. I can do this locally, but not sure why it stops here.

**Comment by rodluger** [comment]
I don't have time to look into this in detail until next week, but the 4kb
size probably means you didn't download the file but instead a 404 html
page or something like that. When workflows fail, they upload an artifact
automatically to GitHub Actions containing a tarball with the contents of
the src directory. Try downloading that and inspecting the dataset file --
should help you debug the problem. Let me know what you find.

**Comment by grburgess** [comment]
I was able to get around the problem by adding -L to curl as its seems that it was redirecting. However, the issue now is that at the end of the process, the artifact upload tries to add the large file which is larger than what git allows. Would this also be the case for normal (non-sandbox) Zenodo? I suppose there is a way to modify or add a rule that would keep this from happening in the end. I am just not sure where to look.

**Comment by rodluger** [comment]
The debugging artifact [shouldn't upload anything larger than 5MB](https://github.com/rodluger/showyourwork/blob/d386d4a0dc94ec4bc04cde027a8fe9badcd46c6d/showyourwork-action/src/onerror.js#L18). Perhaps you mean the arxiv tarball? If so, simply add the file to the `arxiv_tarball_exclude` option of the config file (see [here](https://showyourwork.readthedocs.io/en/v0.2.2/config/#arxiv-tarball-exclude)). Let me know if that works!

**Comment by grburgess** [comment]
Exactly:

```bash
3 files changed, 0 insertions(+), 0 deletions(-)
[2949](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2949)
   create mode 100644 arxiv.tar.gz
[2950](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2950)
   create mode 100644 dag.pdf
[2951](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2951)
   create mode 100644 ms.pdf
[2952](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2952)
  remote: error: Trace: d57060859d51a5e0304fcfe9184718df49e1cd1fc7157ba1aff92baf2e9a9111        
[2953](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2953)
  remote: error: See http://git.io/iEPt8g for more information.        
[2954](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2954)
  remote: error: File arxiv.tar.gz is 617.51 MB; this exceeds GitHub's file size limit of 100.00 MB        
[2955](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2955)
  remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com./        
[2956](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2956)
  To https://github.com/grburgess/whim_paper
[2957](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2957)
   ! [remote rejected] main-pdf -> main-pdf (pre-receive hook declined)
[2958](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2958)
  error: failed to push some refs to 'https://github.com/grburgess/whim_paper'
[2959](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2959)
  Total size of all the files uploaded is 758917 bytes
[2960](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2960)
  Finished uploading artifact showyourwork-output. Reported size is 758917 bytes. There were 0 items that failed to upload
[2961](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2961)
  Error: exec: remote: error: Trace: d57060859d51a5e0304fcfe9184718df49e1cd1fc7157ba1aff92baf2e9a9111        
[2962](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2962)
  remote: error: See http://git.io/iEPt8g for more information.        
[2963](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2963)
  remote: error: File arxiv.tar.gz is 617.51 MB; this exceeds GitHub's file size limit of 100.00 MB        
[2964](https://github.com/grburgess/whim_paper/runs/5038595360?check_suite_focus=true#step:3:2964)
  remote: error: GH001: Large files detected. You may want to try Git Large File Storage -

```

I guess when you manually download, it doesn't know to not include this file? Either way, this worked. Thanks!

**Comment by rodluger** [comment]
That's right -- showyourwork only excludes things it knows for sure are datasets based on info in the yaml file.
