### ISSUE TITLE
Incompatibility of jinja2==2.11.3 with latest markupsafe

### ISSUE THREAD

**Issue by adonath** [rodluger/showyourwork#80]
First thanks for this very nice project! We were happy to use it for writing our paper about our software. Recently we started to see CI fails [like this](https://github.com/gammapy/gammapy-v1.0-paper/runs/5254005242?check_suite_focus=true#step:3:1875). The issue should show up when re-triggering the CI in this repo (or the example templates) as well.

After a quick search I noticed it is due to an incompatibility of `jinja2==2.11.3` with the latest `markupsafe` (see https://github.com/pallets/markupsafe/issues/282). The showyourwork stylesheet rule uses a custom [conda environment file](https://github.com/rodluger/showyourwork/blob/main/workflow/rules/stylesheet.smk#L20), which cannot be updated by the downstream projects. If I'm not mistaken an upstream fix should be required, either by updating the `jinja2` version or pinning `markupsafe` as well.

**Comment by adrn** [comment]
Confirming that I see this too. My fix was to activate the conda environment that snakemake generates, and pin markupsafe to an earlier version with `pip install markupsafe==2.0`. But agreed that this requires a fix in showyourwork!

**Comment by rodluger** [comment]
Thanks for bringing this up. I'll look into it tomorrow.

**Comment by rodluger** [comment]
Fixed in `v0.2.3`. Can one of you confirm?

**Comment by adonath** [comment]
Thanks a lot @rodluger for the quick response and fix! I can confirm the CI in your repo is working again.
