### ISSUE TITLE
Custom manuscript name still turns into "ms.pdf"

### ISSUE THREAD

**Issue by adrn** [rodluger/showyourwork#82]
I'm using the functionality to use a [custom manuscript name](https://showyourwork.readthedocs.io/en/stable/custom), but after the build process, the article pdf file is still names "ms.pdf". Is there a way to have the generated pdf file end up with the same name as the article file?

**Comment by rodluger** [comment]
I've implemented this in the next version, to be released in the next month or so. How badly do you need this feature right now?
